
name: Deploy

on:
  push:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MEILISEARCH_URL: ${{ secrets.MEILISEARCH_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.0
      - name: Install
        run: pnpm install

      - name: Build
        run: |
          pnpm run build
          node scripts/postBuild.js

      - name: Export
        run: pnpm run export

      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
