
name: Deploy

on:
  push:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MEILISEARCH_URL: ${{ secrets.MEILISEARCH_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.0
      - name: Install
        run: pnpm install

      - name: Build
         run: pnpm run build
         run: node scripts/postBuild.js

      - name: Export
         run: pnpm run export
