
name: Deploy

on:
  push:
    branches: [ v1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.0
      env:
        MEILISEARCH_URL: ${{ secrets.MEILISEARCH_URL }}
      - run: echo hello world!
      - run: pnpm --version
      - run: echo $MEILISEARCH_URL
      - run: pnpm install
      - run: pnpm run build
      - run: echo Done.
